# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto.S3BotoStorage(acl=b'private'), upload_to=b''),
        ),
    ]
