# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20171020_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto.S3BotoStorage(acl=b'private'), upload_to=b'media_lists/%Y/%m/%d'),
        ),
    ]
