# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_auto_20171102_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('original_name', models.TextField(default=b'')),
                ('file_name', models.TextField(default=b'')),
                ('url', models.URLField(default=b'')),
                ('file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto.S3BotoStorage(acl=b'private'), upload_to=b'attachments/%Y/%m/%d')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
