# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_emailimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailimage',
            name='url',
        ),
        migrations.AlterField(
            model_name='emailimage',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto.S3BotoStorage(acl=b'public-read'), upload_to=b'image/%Y/%m/%d'),
        ),
    ]
