# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20171107_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.TextField(default=b''),
        ),
    ]
