# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database_contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.TextField(blank=True, default=b'')),
                ('bio', models.TextField(blank=True, default=b'')),
                ('type_id', models.TextField(blank=True, default=b'')),
                ('url', models.URLField(blank=True, default=b'')),
                ('type_name', models.TextField(blank=True, default=b'')),
                ('network', models.TextField(blank=True, default=b'')),
                ('followers', models.IntegerField(blank=True, default=0)),
                ('user_id', models.TextField(blank=True, default=b'')),
                ('following', models.IntegerField(blank=True, default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WritingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('beats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('occasional_beats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('is_freelancer', models.BooleanField(default=False)),
                ('is_influencer', models.BooleanField(default=False)),
                ('rss', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='databasecontact',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_contacts.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='databasecontact',
            name='digital_footprint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_contacts.DigitalFootprint'),
        ),
        migrations.AddField(
            model_name='databasecontact',
            name='social_profiles',
            field=models.ManyToManyField(blank=True, related_name='_databasecontact_social_profiles_+', to='database_contacts.SocialProfile'),
        ),
        migrations.AddField(
            model_name='databasecontact',
            name='writing_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_contacts.WritingInformation'),
        ),
    ]
