# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_contacts', '0003_auto_20171025_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdeduced',
            name='likelihood',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
