# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_contacts', '0004_locationdeduced_likelihood'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasecontact',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='databasecontact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
