# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_contacts', '0005_auto_20171025_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'contact-infos'},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name_plural': 'continents'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='demographic',
            options={'verbose_name_plural': 'demographics'},
        ),
        migrations.AlterModelOptions(
            name='locationdeduced',
            options={'verbose_name_plural': 'location-deduceds'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='socialprofile',
            options={'verbose_name_plural': 'social-profiles'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'states'},
        ),
        migrations.AlterModelOptions(
            name='writinginformation',
            options={'verbose_name_plural': 'writing-informations'},
        ),
    ]
