# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_contacts', '0006_auto_20171026_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writinginformation',
            name='beats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='writinginformation',
            name='rss',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
