# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
