# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldsmap',
            name='name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='customfieldsmap',
            name='value',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='_medialist_client_+', to='users.Client'),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='client_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_medialist_contacts_+', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='fields_map',
            field=models.ManyToManyField(blank=True, related_name='_medialist_fields_map_+', to='lists.CustomFieldsMap'),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files.File'),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Team'),
        ),
    ]
