# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20171020_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialist',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files.File'),
        ),
        migrations.AlterField(
            model_name='medialist',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Team'),
        ),
    ]
