# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20171024_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialist',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=b'', max_length=200), blank=True, default=list, size=None),
        ),
    ]
