# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20171109_0220'),
        ('lists', '0008_auto_20171024_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medialist',
            name='client',
        ),
        migrations.AddField(
            model_name='medialist',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='_medialist_clients_+', to='users.Client'),
        ),
    ]
