# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_customfieldsmap_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfieldsmap',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='medialist',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='medialist',
            name='fields',
        ),
    ]
