# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 19:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 11, 19, 5, 18, 142776)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agency',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 10, 11, 19, 5, 21, 207142)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 11, 19, 5, 31, 274914)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 10, 11, 19, 5, 33, 581884)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='administrators',
            field=models.ManyToManyField(related_name='_agency_administrators_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employers',
            field=models.ManyToManyField(related_name='_userprofile_employers_+', to='users.Agency'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
