# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 21:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20171011_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(default=b'')),
                ('max_members', models.IntegerField(default=0)),
                ('admins', models.ManyToManyField(related_name='_team_admins_+', to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Agency')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='_team_members_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_alias',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_signature',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_signatures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='external_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='get_daily_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='outlook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='outlook_username',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ManyToManyField(related_name='_userprofile_team_+', to='users.Team'),
        ),
    ]
