# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-12 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20171012_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.TextField(default=b'')),
                ('stripe_plan_id', models.TextField(default=b'')),
                ('has_trial', models.BooleanField(default=False)),
                ('is_on_trial', models.BooleanField(default=False)),
                ('is_agency', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'billings',
            },
        ),
    ]
