# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-12 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='team',
            new_name='agency',
        ),
    ]
