# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171012_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='stripe_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='billing',
            name='stripe_plan_id',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
