# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171013_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='live_access_token',
            field=models.TextField(default=b''),
        ),
    ]
