# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171020_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Billing'),
        ),
    ]
