# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_billing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'users'},
        ),
    ]
