# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171024_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_expire_feedback',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_expire_reason',
            field=models.TextField(default=b''),
        ),
    ]
