# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20171030_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='api_key',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_alias',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_signature',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employers',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_employers_+', to='users.Agency'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='live_access_token',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='outlook_username',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_team_+', to='users.Team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trial_expire_feedback',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trial_expire_reason',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
