# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20171031_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Team'),
        ),
    ]
