# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20171102_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail_access_token',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_expires_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_google_code',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_refresh_token',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_token_type',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_username',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
