# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20171108_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='outlook_expires_in',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='outlook_refresh_token',
        ),
    ]
