# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20171109_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='outlook_email_provider',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
