# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userprofile_gmail_nylas_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gmaiL_nylas_code',
            new_name='gmail_nylas_code',
        ),
    ]
