# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20171109_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcode',
            options={'verbose_name_plural': 'email-codes'},
        ),
    ]
