# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20171110_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_signatures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None),
        ),
    ]
