# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        ('contacts', '0003_auto_20171013_1630'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20171013_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('feed_url', models.TextField(default=b'')),
                ('valid_feed', models.BooleanField(default=False)),
                ('running', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contacts.Contact')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('list_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lists.MediaList')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publications.Publication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
