# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20171020_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name_plural': 'feeds'},
        ),
        migrations.AlterField(
            model_name='feed',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_url',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='feed',
            name='list_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lists.MediaList'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publications.Publication'),
        ),
    ]
