# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20171027_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='list_in',
        ),
    ]
