# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 00:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20171012_2353'),
        ('publications', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.TextField(default=b'')),
                ('last_name', models.TextField(default=b'')),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(default=b'')),
                ('linkedin', models.TextField(default=b'')),
                ('twitter', models.TextField(default=b'')),
                ('instagram', models.TextField(default=b'')),
                ('websites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('blog', models.TextField(default=b'')),
                ('twitter_invalid', models.BooleanField(default=False)),
                ('instagram_invalid', models.BooleanField(default=False)),
                ('twitter_private', models.BooleanField(default=False)),
                ('instagram_private', models.BooleanField(default=False)),
                ('location', models.TextField(default=b'')),
                ('phone_number', models.TextField(default=b'')),
                ('is_outdated', models.BooleanField(default=False)),
                ('email_bounced', models.BooleanField(default=False)),
                ('is_master_contact', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('linkedin_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Client')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomContactField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(default=b'')),
                ('value', models.TextField(default=b'')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='custom_fields',
            field=models.ManyToManyField(related_name='_contact_custom_fields_+', to='contacts.CustomContactField'),
        ),
        migrations.AddField(
            model_name='contact',
            name='employers',
            field=models.ManyToManyField(related_name='_contact_employers_+', to='publications.Publication'),
        ),
        migrations.AddField(
            model_name='contact',
            name='past_employers',
            field=models.ManyToManyField(related_name='_contact_past_employers_+', to='publications.Publication'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='contact',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Team'),
        ),
    ]
