# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='blog',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, related_name='_contact_custom_fields_+', to='contacts.CustomContactField'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='employers',
            field=models.ManyToManyField(blank=True, related_name='_contact_employers_+', to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='past_employers',
            field=models.ManyToManyField(blank=True, related_name='_contact_past_employers_+', to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Team'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='customcontactfield',
            name='name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='customcontactfield',
            name='value',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
