# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 16:30
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171013_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
