# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20171027_0040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([]),
        ),
    ]
