# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('smtp_server', models.TextField(default=b'')),
                ('smtp_port_tls', models.IntegerField(default=0)),
                ('smtp_port_ssl', models.IntegerField(default=0)),
                ('smtp_ssl_tls', models.BooleanField(default=False)),
                ('imap_server', models.TextField(default=b'')),
                ('imap_port_tls', models.IntegerField(default=0)),
                ('imap_port_ssl', models.IntegerField(default=0)),
                ('imap_ssl_tls', models.BooleanField(default=False)),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
