# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20171013_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
