# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20171013_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Client'),
        ),
    ]
