# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20171013_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='_email_attachments_+', to='files.File'),
        ),
        migrations.AlterField(
            model_name='email',
            name='base_subject',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='batch_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='clicked',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='first_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='email',
            name='gmail_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='gmail_thread_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='last_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='method',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='opened',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='email',
            name='sendgrid_clicked',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='sendgrid_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='sendgrid_opened',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='sparkpost_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='imap_port_ssl',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='imap_port_tls',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='imap_server',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_port_ssl',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_port_tls',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_server',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
