# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20171013_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'emails'},
        ),
    ]
