# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_auto_20171020_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name_plural': 'email-settings'},
        ),
    ]
