# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_auto_20171102_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSettings',
            new_name='EmailSetting',
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name_plural': 'campaigns'},
        ),
    ]
