# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_auto_20171102_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='gmail_id',
            new_name='nylas_id',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='gmail_thread_id',
            new_name='nylas_thread_id',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sparkpost_id',
        ),
    ]
