# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_auto_20171109_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='nylas_account_id',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
