# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_email_nylas_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsetting',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='EmailSetting',
        ),
    ]
