# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_auto_20171109_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='unique_replies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
