# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_campaign_unique_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='replies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
