# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0018_auto_20171110_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='bounces',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='opens',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='unique_clicks',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='unique_opens',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='unique_replies',
        ),
    ]
