# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0019_auto_20171110_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bounces',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='delivered',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='opens',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unique_clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unique_opens',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unique_replies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
