# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0020_auto_20171110_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='replies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
